import type { CategoryEmbedding, Post, PostType } from "@/lib/generated/prisma";

// Base navigation data structure containing all navigation elements
export type NavigationData = {
  categories: CategoryNode[];
  tags: TagWithMetadata[];
  posts: Post[];
  postTypeCounts: PostTypeCount[];
  totalPosts: number;
  lastUpdated: Date;
};

// Hierarchical category node with nested children
export type CategoryNode = {
  id: string;
  name: string; // kebab-case name for internal use and matching
  displayName: string; // Human-readable name for UI display
  slug: string;
  path: string; // Full path like "ai-tools/developer-tools/llmops"
  parentPath: string | null;
  depth: number;
  postCount: number; // Direct posts in this category
  totalPostCount: number; // Including all nested categories
  children: CategoryNode[];
  embedding?: CategoryEmbedding; // Optional embedding data for ML features
  postTypes?: PostTypeDistribution; // Distribution of post types
  isExpanded?: boolean; // UI state for tree expansion
  isActive?: boolean; // UI state for current selection
};

// Tag with additional metadata for intelligent display
export type TagWithMetadata = {
  id: string;
  name: string;
  slug: string;
  postCount: number;
  postTypes: PostTypeDistribution;
  weight: number; // Normalized weight for tag cloud (0-1)
  cluster?: string; // Optional cluster identifier for grouping
  isAutoGenerated?: boolean; // For tags like "findings-summary"
  lastUsed?: Date;
  trending?: boolean;
};

// Distribution of posts by type
export type PostTypeDistribution = {
  CONCRETE: number;
  BLOG: number;
  FINDING: number;
  SIGHT: number;
};

// Count of posts by type for filtering
export type PostTypeCount = {
  type: PostType;
  count: number;
  percentage: number;
};

// Filter state for navigation
export type NavigationFilters = {
  postTypes: PostType[]; // Active post type filters
  categories: string[]; // Selected category slugs
  tags: string[]; // Selected tag slugs
  tagMode: "AND" | "OR"; // Tag filter logic
  searchQuery: string;
  dateRange?: DateRange;
  sortBy: SortOption;
};

// Date range for timeline filtering
export type DateRange = {
  start: Date | null;
  end: Date | null;
};

// Sort options for navigation
export type SortOption =
  | "date-desc"
  | "date-asc"
  | "title-asc"
  | "title-desc"
  | "relevance";

// User preferences for navigation
export type NavigationPreferences = {
  expandedCategories: string[]; // Paths of expanded categories
  favoriteCategories: string[]; // Pinned categories
  favoriteTags: string[]; // Pinned tags
  defaultTab: NavigationTab;
  viewMode: NavigationViewMode;
  tagCloudDensity: "compact" | "normal" | "expanded";
  showPostCounts: boolean;
  showEmptyCategories: boolean;
};

// Navigation tabs
export type NavigationTab = "rabbithole" | "categories" | "tags" | "timeline";

// View modes for different layouts
export type NavigationViewMode = "tree" | "flat" | "cloud" | "list";

// Search results with grouped items
export type NavigationSearchResults = {
  categories: CategorySearchResult[];
  tags: TagSearchResult[];
  posts: PostSearchResult[];
  totalResults: number;
  searchTime: number; // milliseconds
};

// Category search result
export type CategorySearchResult = {
  category: CategoryNode;
  matchScore: number;
  matchedIn: "name" | "path";
};

// Tag search result
export type TagSearchResult = {
  tag: TagWithMetadata;
  matchScore: number;
};

// Post search result
export type PostSearchResult = {
  post: Post;
  matchScore: number;
  matchedIn: "title" | "content" | "excerpt";
};

// Smart suggestions based on navigation patterns
export type NavigationSuggestion = {
  type: "category" | "tag" | "post";
  item: CategoryNode | TagWithMetadata | Post;
  reason: SuggestionReason;
  confidence: number; // 0-1
};

// Reasons for suggestions
export type SuggestionReason =
  | "related-content"
  | "similar-embedding"
  | "frequently-visited"
  | "trending"
  | "recently-updated";

// Tag cluster for intelligent grouping
export type TagCluster = {
  id: string;
  name: string;
  tags: TagWithMetadata[];
  commonTheme?: string;
  color?: string; // Optional color coding for UI
};

// Timeline grouping options
export type TimelineGroup = {
  period: "day" | "week" | "month" | "year";
  date: Date;
  posts: Post[];
  postTypes: PostTypeDistribution;
};

// Category tree state for UI management
export type CategoryTreeState = {
  expandedNodes: Set<string>;
  selectedNode: string | null;
  searchQuery: string;
  filteredNodes: Set<string>; // Nodes matching search
  highlightedNode: string | null; // For keyboard navigation
};

// Tag cloud state for UI management
export type TagCloudState = {
  selectedTags: Set<string>;
  hoveredTag: string | null;
  filterMode: "AND" | "OR";
  clusters: TagCluster[];
  viewDensity: "compact" | "normal" | "expanded";
};

// Navigation analytics for tracking usage
export type NavigationAnalytics = {
  categoryClicks: Map<string, number>;
  tagClicks: Map<string, number>;
  searchQueries: string[];
  navigationPaths: NavigationPath[];
};

// Navigation path for tracking user journeys
export type NavigationPath = {
  from: string;
  to: string;
  timestamp: Date;
  type: "category" | "tag" | "search" | "suggestion";
};

// Export all navigation-related types from Prisma for convenience
export type {
  Category,
  CategoryEmbedding,
  Post,
  PostType,
  Tag,
} from "@/lib/generated/prisma";
