import type { CategoryEmbedding, Post, PostType } from "@/lib/generated/prisma";

// Base navigation data structure containing all navigation elements
export interface NavigationData {
  categories: CategoryNode[];
  lastUpdated: Date;
  posts: Post[];
  postTypeCounts: PostTypeCount[];
  tags: TagWithMetadata[];
  totalPosts: number;
}

// Hierarchical category node with nested children
export interface CategoryNode {
  children: CategoryNode[];
  depth: number;
  displayName: string; // Human-readable name for UI display
  embedding?: CategoryEmbedding; // Optional embedding data for ML features
  id: string;
  isActive?: boolean; // UI state for current selection
  isExpanded?: boolean; // UI state for tree expansion
  name: string; // kebab-case name for internal use and matching
  parentPath: string | null;
  path: string; // Full path like "ai-tools/developer-tools/llmops"
  postCount: number; // Direct posts in this category
  postTypes?: PostTypeDistribution; // Distribution of post types
  slug: string;
  totalPostCount: number; // Including all nested categories
}

// Tag with additional metadata for intelligent display
export interface TagWithMetadata {
  cluster?: string; // Optional cluster identifier for grouping
  id: string;
  isAutoGenerated?: boolean; // For tags like "findings-summary"
  lastUsed?: Date;
  name: string;
  postCount: number;
  postTypes: PostTypeDistribution;
  slug: string;
  trending?: boolean;
  weight: number; // Normalized weight for tag cloud (0-1)
}

// Distribution of posts by type
export interface PostTypeDistribution {
  BLOG: number;
  CONCRETE: number;
  FINDING: number;
  SIGHT: number;
}

// Count of posts by type for filtering
export interface PostTypeCount {
  count: number;
  percentage: number;
  type: PostType;
}

// Filter state for navigation
export interface NavigationFilters {
  categories: string[]; // Selected category slugs
  dateRange?: DateRange;
  postTypes: PostType[]; // Active post type filters
  searchQuery: string;
  sortBy: SortOption;
  tagMode: "AND" | "OR"; // Tag filter logic
  tags: string[]; // Selected tag slugs
}

// Date range for timeline filtering
export interface DateRange {
  end: Date | null;
  start: Date | null;
}

// Sort options for navigation
export type SortOption =
  | "date-desc"
  | "date-asc"
  | "title-asc"
  | "title-desc"
  | "relevance";

// User preferences for navigation
export interface NavigationPreferences {
  defaultTab: NavigationTab;
  expandedCategories: string[]; // Paths of expanded categories
  favoriteCategories: string[]; // Pinned categories
  favoriteTags: string[]; // Pinned tags
  showEmptyCategories: boolean;
  showPostCounts: boolean;
  tagCloudDensity: "compact" | "normal" | "expanded";
  viewMode: NavigationViewMode;
}

// Navigation tabs
export type NavigationTab = "rabbithole" | "categories" | "tags" | "timeline";

// View modes for different layouts
export type NavigationViewMode = "tree" | "flat" | "cloud" | "list";

// Search results with grouped items
export interface NavigationSearchResults {
  categories: CategorySearchResult[];
  posts: PostSearchResult[];
  searchTime: number; // milliseconds
  tags: TagSearchResult[];
  totalResults: number;
}

// Category search result
export interface CategorySearchResult {
  category: CategoryNode;
  matchedIn: "name" | "path";
  matchScore: number;
}

// Tag search result
export interface TagSearchResult {
  matchScore: number;
  tag: TagWithMetadata;
}

// Post search result
export interface PostSearchResult {
  matchedIn: "title" | "content" | "excerpt";
  matchScore: number;
  post: Post;
}

// Smart suggestions based on navigation patterns
export interface NavigationSuggestion {
  confidence: number; // 0-1
  item: CategoryNode | TagWithMetadata | Post;
  reason: SuggestionReason;
  type: "category" | "tag" | "post";
}

// Reasons for suggestions
export type SuggestionReason =
  | "related-content"
  | "similar-embedding"
  | "frequently-visited"
  | "trending"
  | "recently-updated";

// Tag cluster for intelligent grouping
export interface TagCluster {
  color?: string; // Optional color coding for UI
  commonTheme?: string;
  id: string;
  name: string;
  tags: TagWithMetadata[];
}

// Timeline grouping options
export interface TimelineGroup {
  date: Date;
  period: "day" | "week" | "month" | "year";
  posts: Post[];
  postTypes: PostTypeDistribution;
}

// Category tree state for UI management
export interface CategoryTreeState {
  expandedNodes: Set<string>;
  filteredNodes: Set<string>; // Nodes matching search
  highlightedNode: string | null; // For keyboard navigation
  searchQuery: string;
  selectedNode: string | null;
}

// Tag cloud state for UI management
export interface TagCloudState {
  clusters: TagCluster[];
  filterMode: "AND" | "OR";
  hoveredTag: string | null;
  selectedTags: Set<string>;
  viewDensity: "compact" | "normal" | "expanded";
}

// Navigation analytics for tracking usage
export interface NavigationAnalytics {
  categoryClicks: Map<string, number>;
  navigationPaths: NavigationPath[];
  searchQueries: string[];
  tagClicks: Map<string, number>;
}

// Navigation path for tracking user journeys
export interface NavigationPath {
  from: string;
  timestamp: Date;
  to: string;
  type: "category" | "tag" | "search" | "suggestion";
}

// Export all navigation-related types from Prisma for convenience
export type {
  Category,
  CategoryEmbedding,
  Post,
  PostType,
  Tag,
} from "@/lib/generated/prisma";
