"use client";

import { useCallback, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { TagWithMetadata } from "@/types/navigation";

// import { usePostStackActions } from "@/components/post-stack/post-stack-provider-xstate" // For future post navigation

type TagCloudProps = {
  tags: TagWithMetadata[];
  onTagClick?: (tag: TagWithMetadata) => void;
  onNavigate?: () => void;
  density?: "compact" | "normal" | "expanded";
  showPostTypes?: boolean;
  className?: string;
};

export function TagCloud({
  tags,
  onTagClick,
  onNavigate,
  density = "normal",
  showPostTypes = true,
  className,
}: TagCloudProps) {
  // const { addPost } = usePostStackActions() // Will be used when connecting to posts
  const [selectedTags, setSelectedTags] = useState<Set<string>>(new Set());
  const [hoveredTag, setHoveredTag] = useState<string | null>(null);

  // Calculate font size based on weight (normalized 0-1)
  const getFontSize = (weight: number) => {
    const minSize = density === "compact" ? 10 : 11;
    let maxSize = 20;
    if (density === "compact") {
      maxSize = 18;
    } else if (density === "expanded") {
      maxSize = 24;
    }
    return Math.floor(minSize + (maxSize - minSize) * weight);
  };

  // Group tags by weight ranges for better visual organization
  const tagGroups = useMemo(() => {
    const groups = {
      large: [] as TagWithMetadata[], // weight > 0.7
      medium: [] as TagWithMetadata[], // weight 0.3-0.7
      small: [] as TagWithMetadata[], // weight < 0.3
    };

    tags.forEach((tag) => {
      if (tag.weight > 0.7) {
        groups.large.push(tag);
      } else if (tag.weight > 0.3) {
        groups.medium.push(tag);
      } else {
        groups.small.push(tag);
      }
    });

    // Sort within each group alphabetically
    Object.values(groups).forEach((group) => {
      group.sort((a, b) => a.name.localeCompare(b.name));
    });

    return groups;
  }, [tags]);

  // Identify auto-generated tags
  const autoGeneratedTags = useMemo(
    () =>
      new Set(tags.filter((tag) => tag.isAutoGenerated).map((tag) => tag.slug)),
    [tags]
  );

  const handleTagClick = useCallback(
    (tag: TagWithMetadata) => {
      // Toggle selection
      setSelectedTags((prev) => {
        const next = new Set(prev);
        if (next.has(tag.slug)) {
          next.delete(tag.slug);
        } else {
          next.add(tag.slug);
        }
        return next;
      });

      // Trigger navigation callback
      onTagClick?.(tag);
      onNavigate?.();
    },
    [onTagClick, onNavigate]
  );

  // Get terminal-style tag display
  const getTagDisplay = (tag: TagWithMetadata) => {
    const fontSize = getFontSize(tag.weight);
    const isSelected = selectedTags.has(tag.slug);
    // const isHovered = hoveredTag === tag.slug // For future hover effects
    const isAutoGen = autoGeneratedTags.has(tag.slug);

    // Post type indicators
    const typeIndicator =
      showPostTypes && tag.postTypes
        ? (() => {
            const types: string[] = [];
            if (tag.postTypes.FINDING > 0) {
              types.push("F");
            }
            if (tag.postTypes.SIGHT > 0) {
              types.push("S");
            }
            if (tag.postTypes.BLOG > 0) {
              types.push("B");
            }
            if (tag.postTypes.CONCRETE > 0) {
              types.push("C");
            }
            return types.length > 0 ? `[${types.join("")}]` : "";
          })()
        : "";

    return (
      <Button
        aria-label={`${tag.name} tag with ${tag.postCount} posts`}
        aria-pressed={isSelected}
        className={cn(
          "m-1 p-2 font-mono transition-all duration-200",
          "border border-white/20",
          "hover:border-primary/70 hover:bg-primary/10 hover:text-primary",
          isSelected && "terminal-active-item",
          isAutoGen && "border-dashed text-white/40",
          !(isSelected || isAutoGen) && "text-white/70"
        )}
        key={tag.slug}
        onClick={() => handleTagClick(tag)}
        onMouseEnter={() => setHoveredTag(tag.slug)}
        onMouseLeave={() => setHoveredTag(null)}
        style={{ fontSize: `${fontSize}px` }}
        variant="ghost"
      >
        <span className="flex items-center gap-1">
          {isAutoGen && <span className="text-white/30">◊</span>}
          <span>{tag.name}</span>
          <span className="text-xs opacity-60">({tag.postCount})</span>
          {typeIndicator && (
            <span className="terminal-prompt-muted ml-1 text-xs">
              {typeIndicator}
            </span>
          )}
        </span>
      </Button>
    );
  };

  // Calculate cloud statistics
  const stats = useMemo(() => {
    const selected = selectedTags.size;
    const total = tags.length;
    const totalPosts = tags.reduce((sum, tag) => sum + tag.postCount, 0);
    const avgPostsPerTag = total > 0 ? Math.round(totalPosts / total) : 0;

    return { selected, total, totalPosts, avgPostsPerTag };
  }, [tags, selectedTags]);

  return (
    <div className={cn("flex h-full flex-col", className)}>
      {/* Terminal header */}
      <div className="flex-shrink-0 border-white/10 border-b p-3">
        <div className="mb-2 flex items-center gap-2 text-white/40 text-xs">
          <span className="terminal-prompt">❯</span>
          <span>./tags --cloud --weight</span>
        </div>
        <div className="flex items-center justify-between text-xs">
          <span className="text-white/60">
            {stats.total} tags • {stats.totalPosts} posts
          </span>
          <div className="flex gap-3">
            <button
              aria-label="Clear selected tags"
              className={cn(
                "text-white/40 transition-colors hover:text-white/60",
                selectedTags.size > 0 && "terminal-interactive"
              )}
              disabled={selectedTags.size === 0}
              onClick={() => setSelectedTags(new Set())}
              type="button"
            >
              [clear]
            </button>
            <span className="text-white/40">density: {density}</span>
          </div>
        </div>
      </div>

      {/* Tag cloud */}
      <div className="custom-scrollbar min-h-0 flex-1 overflow-y-auto p-4">
        {tags.length === 0 ? (
          <div className="text-center text-white/40 text-xs">
            <span className="mb-2 block">∅</span>
            <span>No tags found</span>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Large tags */}
            {tagGroups.large.length > 0 && (
              <div>
                <div className="mb-2 font-mono text-white/30 text-xs">
                  ▪ popular ({tagGroups.large.length})
                </div>
                <div className="flex flex-wrap items-center">
                  {tagGroups.large.map((tag) => getTagDisplay(tag))}
                </div>
              </div>
            )}

            {/* Medium tags */}
            {tagGroups.medium.length > 0 && (
              <div>
                <div className="mb-2 font-mono text-white/30 text-xs">
                  ▪ common ({tagGroups.medium.length})
                </div>
                <div className="flex flex-wrap items-center">
                  {tagGroups.medium.map((tag) => getTagDisplay(tag))}
                </div>
              </div>
            )}

            {/* Small tags */}
            {tagGroups.small.length > 0 && (
              <div>
                <div className="mb-2 font-mono text-white/30 text-xs">
                  ▪ specific ({tagGroups.small.length})
                </div>
                <div className="flex flex-wrap items-center">
                  {tagGroups.small.map((tag) => getTagDisplay(tag))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Hover info - Fixed height to prevent layout shifts */}
      <div className="h-12 flex-shrink-0 border-white/10 border-t p-3 text-xs">
        {hoveredTag ? (
          <div className="text-white/60">
            {(() => {
              const tag = tags.find((t) => t.slug === hoveredTag);
              if (!tag) {
                return null;
              }

              return (
                <div className="flex items-center justify-between">
                  <span>
                    {tag.name}: {tag.postCount} posts
                  </span>
                  {tag.postTypes && (
                    <span className="terminal-prompt-muted">
                      F:{tag.postTypes.FINDING} S:{tag.postTypes.SIGHT}
                      B:{tag.postTypes.BLOG} C:{tag.postTypes.CONCRETE}
                    </span>
                  )}
                </div>
              );
            })()}
          </div>
        ) : (
          <div className="text-white/40">hover over tags for details</div>
        )}
      </div>

      {/* Status bar */}
      <div className="h-12 flex-shrink-0 border-white/10 border-t p-3">
        <div className="flex items-center justify-between text-white/40 text-xs">
          <span>
            {stats.selected > 0
              ? `selected: ${stats.selected} tags`
              : "click tags to select"}
          </span>
          <span className="terminal-prompt">
            avg: {stats.avgPostsPerTag}/tag
          </span>
        </div>
      </div>
    </div>
  );
}
