/**
 * Next.js Cache Components wrappers for stable navigation aggregates.
 *
 * Each exported function is wrapped with `'use cache'` so PPR can prerender
 * downstream UI. Cache keys come from arguments + closure automatically.
 *
 * Tag conventions:
 *   - `nav`: anything backing sidebar/timeline/tag-cloud aggregates.
 *   - `posts`: anything that depends on the published post set.
 *
 * Invalidate via `lib/cache-invalidation.ts` after sync writes.
 */

import { cacheLife, cacheTag } from "next/cache";
import { PostStatus, PostType } from "@/lib/generated/prisma";
import { CategoryTreeBuilder } from "@/lib/navigation/category-tree-builder";
import { POST_DATE_DESC } from "@/lib/post-ordering";
import {
  getAllAvailablePostIds as getAllAvailablePostIdsRaw,
  getAllConcretePostIds as getAllConcretePostIdsRaw,
  getAllNavigablePostsWithCategories as getAllNavigablePostsWithCategoriesRaw,
  getAllPostsByLastEdited as getAllPostsByLastEditedRaw,
} from "@/lib/posts";
import { prisma } from "@/lib/prisma";
import type {
  CategoryNode,
  PostTypeCount,
  TagWithMetadata,
} from "@/types/navigation";

// ===== NAV AGGREGATES (cacheLife: hours) =====

export async function getCachedAllAvailablePostIds(): Promise<string[]> {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:available-post-ids");

  return await getAllAvailablePostIdsRaw();
}

export async function getCachedAllConcretePostIds(): Promise<string[]> {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:concrete-post-ids");

  return await getAllConcretePostIdsRaw();
}

export async function getCachedAllPostsByLastEdited() {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:timeline");

  return await getAllPostsByLastEditedRaw();
}

export async function getCachedAllNavigablePostsWithCategories() {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:navigable-posts");

  return await getAllNavigablePostsWithCategoriesRaw();
}

/**
 * Nested categories with full post type counts for the navigation tree.
 * Body moved from `lib/actions/navigation-actions.ts` so it can live in a
 * non-"use server" module that supports `'use cache'`.
 */
export async function getCachedNestedCategoriesWithCounts(): Promise<
  CategoryNode[]
> {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:categories");

  // Errors propagate to the action wrapper in `lib/actions/navigation-actions.ts`,
  // which catches and returns []. Catching here would cache the empty fallback for
  // the full `hours` window after a transient DB blip.
  const embeddings = await prisma.categoryEmbedding.findMany({
    orderBy: { path: "asc" },
  });

  const categoryCounts = await prisma.category.findMany({
    include: {
      _count: {
        select: {
          posts: { where: { status: PostStatus.PUBLISHED } },
        },
      },
      posts: {
        where: { status: PostStatus.PUBLISHED },
        select: { type: true },
      },
    },
  });

  const categoryData = categoryCounts.map((cat) => ({
    name: cat.name,
    displayName: cat.displayName,
    postCount: cat._count.posts,
    postTypes: cat.posts.reduce(
      (acc, post) => {
        acc[post.type] = (acc[post.type] || 0) + 1;
        return acc;
      },
      {} as Record<string, number>
    ),
  }));

  const builder = new CategoryTreeBuilder(embeddings, categoryData);
  return builder.buildTree();
}

export async function getCachedTagsWithMetadata(): Promise<TagWithMetadata[]> {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:tags");

  const tags = await prisma.tag.findMany({
    include: {
      posts: {
        where: { status: PostStatus.PUBLISHED },
        select: { type: true },
      },
    },
  });

  const datePatterns = [
    /^findings-\d{4}-\d{2}-\d{2}$/,
    /^sights-\d{4}-\d{2}-\d{2}$/,
    /^findings-summary/,
    /^sights-summary/,
    /^\d{4}-\d{2}-\d{2}$/,
    /^\d{8}$/,
  ];

  const filteredTags = tags.filter((tag) => {
    const isExcluded = datePatterns.some(
      (pattern) => pattern.test(tag.slug) || pattern.test(tag.name)
    );
    return !isExcluded && tag.posts.length > 0;
  });

  const maxCount = Math.max(...filteredTags.map((tag) => tag.posts.length), 1);

  return filteredTags.map((tag) => {
    const distribution = { CONCRETE: 0, BLOG: 0, FINDING: 0, SIGHT: 0 };
    tag.posts.forEach((post) => {
      if (post.type in distribution) {
        distribution[post.type]++;
      }
    });

    return {
      id: tag.id,
      name: tag.name,
      slug: tag.slug,
      postCount: tag.posts.length,
      postTypes: distribution,
      weight: tag.posts.length / maxCount,
      isAutoGenerated: false,
      cluster: undefined,
    } as TagWithMetadata;
  });
}

export async function getCachedPostTypeCounts(): Promise<PostTypeCount[]> {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:post-type-counts");

  const counts = await prisma.post.groupBy({
    by: ["type"],
    where: { status: PostStatus.PUBLISHED },
    _count: { type: true },
  });

  const total = counts.reduce((sum, item) => sum + item._count.type, 0);

  return counts.map((item) => ({
    type: item.type,
    count: item._count.type,
    percentage: total > 0 ? (item._count.type / total) * 100 : 0,
  }));
}

export interface ChroniclePost {
  categories: Array<{ name: string }>;
  id: string;
  originalDate: Date;
  slug: string;
  tags: Array<{ name: string }>;
  title: string;
  type: PostType;
}

export async function getCachedChroniclePosts(): Promise<ChroniclePost[]> {
  "use cache";
  cacheLife("hours");
  cacheTag("nav", "posts", "nav:chronicle");

  const posts = await prisma.post.findMany({
    where: {
      status: PostStatus.PUBLISHED,
      type: { in: [PostType.FINDING, PostType.SIGHT] },
      NOT: { originalDate: null },
    },
    include: {
      tags: { select: { name: true } },
      categories: { select: { name: true } },
    },
    orderBy: POST_DATE_DESC,
  });

  return posts.map((p) => ({
    id: p.slug,
    slug: p.slug,
    title: p.title,
    type: p.type,
    // biome-ignore lint/style/noNonNullAssertion: query filters NOT: { originalDate: null }
    originalDate: p.originalDate!,
    tags: p.tags?.map((t) => ({ name: t.name })) ?? [],
    categories: p.categories?.map((c) => ({ name: c.name })) ?? [],
  }));
}
