#!/usr/bin/env bash
# Phase 2.5: emit the coverage_matrix.md skeleton with all smell rules.
# The coverage-mapper subagent fills in Notes / verdicts / etc.
# Usage: generate-coverage-matrix.sh <project>
set -euo pipefail

project="${1:?usage: generate-coverage-matrix.sh <project>}"
cd "$project"
ws=".repo_janitor_workspace"
out="$ws/coverage_matrix.md"

# Smell rules from FILE-SMELLS.md (subset; enumerate the most important)
rules=(
    sqlite-db
    sqlite-wal-shm
    binary-elf
    compiled-out
    nohup-leak
    scratch-script
    skill-output
    progress-report
    planning-doc
    multi-llm-plan-cluster
    agent-output
    audit-report
    dual-format-asset
    format-patch-blob
    editor-backup
    os-detritus
    coverage-output
    secret-suspect
    secret-leak
    random-json-artifact
    random-jsonl-artifact
    txt-architecture-summary
    runbook-or-recovery
    ad-hoc-test-fixture-stub
    dot-pre-skill-state
    archetype-protected
    referenced-by-build
    referenced-by-tests
    0-byte-stub
    mailbox-format-patch
    target-with-custom-suffix
    profiling-artifact
    agent-tooling-state
    llm-scratch-note
    test-bench-db
    compile-output-at-root
    numeric-or-shell-escape-name
    submodule-scratch
    test-fixture-stranded
    visualization-script
    deploy-script
    binary-zip
    binary-mach-o
    python-cache
    rust-build-leakage
    node-modules-leakage
)

{
    echo "## Smell-rule coverage matrix — $(basename "$project") $(date -u +%Y-%m-%d)"
    echo ""
    echo "| Smell rule | Status | Hit count | Verdict distribution | Evidence | Notes |"
    echo "|------------|--------|----------:|----------------------|----------|-------|"

    for rule in "${rules[@]}"; do
        # Count candidates with this tag. Match exact tags (comma-bounded) to avoid
        # `binary-elf` matching `binary-elf-extension` etc.
        if [[ -f "$ws/candidates.tsv" ]]; then
            hits=$(tail -n +2 "$ws/candidates.tsv" \
                   | awk -F'\t' -v r=",$rule," '("," $6 ",") ~ r' \
                   | wc -l)
        else
            hits=0
        fi

        if [[ "$hits" -eq 0 ]]; then
            status="<TBD; coverage-mapper will mark missing or n/a>"
        else
            status="present"
        fi

        echo "| $rule | $status | $hits | TBD | TBD | TBD |"
    done

    echo ""
    echo "Generated by scripts/generate-coverage-matrix.sh."
    echo "The coverage-mapper subagent fills in Status (missing vs n/a), verdict distribution, evidence, and notes."
} > "$out"

echo "skeleton written to $out"
